/**
 * lib/teamNamesFr.js
 * Traduction des noms d'équipes ESPN (shortDisplayName / displayName) → français.
 * Utilisé côté serveur (api/cron/goals.js) et côté client (src/).
 * ESPN utilise ses propres abréviations en anglais — ce fichier fait le pont.
 */

const ESPN_NAMES_FR = {
  // ── Équipes nationales (Coupe du monde / Nations) ─────────────────────────
  'France':                'France',
  'Argentina':             'Argentine',
  'Brazil':                'Brésil',
  'England':               'Angleterre',
  'Germany':               'Allemagne',
  'Spain':                 'Espagne',
  'Portugal':              'Portugal',
  'Netherlands':           'Pays-Bas',
  'Belgium':               'Belgique',
  'Croatia':               'Croatie',
  'Morocco':               'Maroc',
  'Japan':                 'Japon',
  'Senegal':               'Sénégal',
  'Switzerland':           'Suisse',
  'United States':         'États-Unis',
  'USA':                   'États-Unis',
  'South Korea':           'Corée du Sud',
  'Korea Republic':        'Corée du Sud',
  'Australia':             'Australie',
  'Mexico':                'Mexique',
  'Ecuador':               'Équateur',
  'Uruguay':               'Uruguay',
  'Colombia':              'Colombie',
  'Chile':                 'Chili',
  'Peru':                  'Pérou',
  'Bolivia':               'Bolivie',
  'Venezuela':             'Venezuela',
  'Paraguay':              'Paraguay',
  'Panama':                'Panama',
  'Costa Rica':            'Costa Rica',
  'Honduras':              'Honduras',
  'Canada':                'Canada',
  'Jamaica':               'Jamaïque',
  'Trinidad and Tobago':   'Trinité-et-Tobago',
  'Haiti':                 'Haïti',
  'Curaçao':               'Curaçao',
  'Qatar':                 'Qatar',
  'Saudi Arabia':          'Arabie Saoudite',
  'Iran':                  'Iran',
  'Iraq':                  'Irak',
  'Jordan':                'Jordanie',
  'Australia':             'Australie',
  'New Zealand':           'Nouvelle-Zélande',
  'Japan':                 'Japon',
  'South Africa':          'Afrique du Sud',
  'Nigeria':               'Nigéria',
  'Egypt':                 'Égypte',
  'Algeria':               'Algérie',
  'Morocco':               'Maroc',
  'Tunisia':               'Tunisie',
  'Senegal':               'Sénégal',
  'Ghana':                 'Ghana',
  'Cameroon':              'Cameroun',
  'Ivory Coast':           "Côte d'Ivoire",
  "Cote d'Ivoire":         "Côte d'Ivoire",
  'DR Congo':              'RD Congo',
  'Congo DR':              'RD Congo',
  'Cape Verde':            'Cap-Vert',
  'Poland':                'Pologne',
  'Denmark':               'Danemark',
  'Serbia':                'Serbie',
  'Ukraine':               'Ukraine',
  'Turkey':                'Turquie',
  'Türkiye':               'Turquie',
  'Scotland':              'Écosse',
  'Hungary':               'Hongrie',
  'Slovakia':              'Slovaquie',
  'Slovenia':              'Slovénie',
  'Austria':               'Autriche',
  'Romania':               'Roumanie',
  'Albania':               'Albanie',
  'Georgia':               'Géorgie',
  'Czech Republic':        'Tchéquie',
  'Czechia':               'Tchéquie',
  'Wales':                 'Pays de Galles',
  'Norway':                'Norvège',
  'Sweden':                'Suède',
  'Finland':               'Finlande',
  'Russia':                'Russie',
  'Uzbekistan':            'Ouzbékistan',
  
  // ── Clubs — Ligue 1 ────────────────────────────────────────────────────────
  'Paris Saint-Germain':   'Paris SG',
  'PSG':                   'Paris SG',
  'Marseille':             'Marseille',
  'Olympique de Marseille':'Marseille',
  'Lyon':                  'Lyon',
  'Olympique Lyonnais':    'Lyon',
  'Monaco':                'Monaco',
  'Lens':                  'Lens',
  'RC Lens':               'Lens',
  'Lille':                 'Lille',
  'LOSC Lille':            'Lille',
  'Nice':                  'Nice',
  'OGC Nice':              'Nice',
  'Rennes':                'Rennes',
  'Stade Rennais':         'Rennes',
  'Nantes':                'Nantes',
  'FC Nantes':             'Nantes',
  'Strasbourg':            'Strasbourg',
  'RC Strasbourg':         'Strasbourg',
  'Toulouse':              'Toulouse',
  'TFC':                   'Toulouse',
  'Brest':                 'Brest',
  'Stade Brestois':        'Brest',
  'Reims':                 'Reims',
  'Le Havre':              'Le Havre',
  'Metz':                  'Metz',
  'FC Metz':               'Metz',
  'Angers':                'Angers',
  'Lorient':               'Lorient',
  'Auxerre':               'Auxerre',
  'Paris FC':              'Paris FC',

  // ── Clubs — Premier League ─────────────────────────────────────────────────
  'Arsenal':               'Arsenal',
  'Chelsea':               'Chelsea',
  'Liverpool':             'Liverpool',
  'Manchester City':       'Man. City',
  'Man City':              'Man. City',
  'Manchester United':     'Man. United',
  'Man United':            'Man. United',
  'Tottenham':             'Tottenham',
  'Tottenham Hotspur':     'Tottenham',
  'Newcastle':             'Newcastle',
  'Newcastle United':      'Newcastle',
  'Aston Villa':           'Aston Villa',
  'Brighton':              'Brighton',
  'Brighton & Hove Albion':'Brighton',
  'West Ham':              'West Ham',
  'West Ham United':       'West Ham',
  'Crystal Palace':        'Crystal Palace',
  'Brentford':             'Brentford',
  'Fulham':                'Fulham',
  'Wolves':                'Wolverhampton',
  'Wolverhampton':         'Wolverhampton',
  'Wolverhampton Wanderers':'Wolverhampton',
  'Everton':               'Everton',
  'Nottingham Forest':     'Nottingham',
  'Nottingham':            'Nottingham',
  'Bournemouth':           'Bournemouth',
  'Burnley':               'Burnley',
  'Sheffield United':      'Sheffield Utd',
  'Luton':                 'Luton',
  'Sunderland':            'Sunderland',
  'Leeds':                 'Leeds',
  'Leeds United':          'Leeds',
  'Leicester':             'Leicester',
  'Leicester City':        'Leicester',
  'Ipswich':               'Ipswich',
  'Ipswich Town':          'Ipswich',

  // ── Clubs — LaLiga ────────────────────────────────────────────────────────
  'Real Madrid':           'Real Madrid',
  'Barcelona':             'Barcelone',
  'FC Barcelona':          'Barcelone',
  'Atletico Madrid':       'Atlético Madrid',
  'Atlético Madrid':       'Atlético Madrid',
  'Athletic Club':         'Athletic Bilbao',
  'Athletic Bilbao':       'Athletic Bilbao',
  'Real Sociedad':         'Real Sociedad',
  'Villarreal':            'Villarreal',
  'Sevilla':               'Séville',
  'Sevilla FC':            'Séville',
  'Real Betis':            'Betis',
  'Betis':                 'Betis',
  'Valencia':              'Valence',
  'Celta Vigo':            'Celta Vigo',
  'Celta':                 'Celta Vigo',
  'Girona':                'Girona',
  'Getafe':                'Getafe',
  'Osasuna':               'Osasuna',
  'Rayo Vallecano':        'Rayo Vallecano',
  'Mallorca':              'Mallorca',
  'Espanyol':              'Espanyol',
  'RCD Espanyol':          'Espanyol',
  'Alaves':                'Alavés',
  'Alavés':                'Alavés',
  'Leganes':               'Leganés',
  'Valladolid':            'Valladolid',

  // ── Clubs — Bundesliga ────────────────────────────────────────────────────
  'Bayern Munich':         'Bayern Munich',
  'Bayern':                'Bayern Munich',
  'Borussia Dortmund':     'Dortmund',
  'Dortmund':              'Dortmund',
  'Bayer Leverkusen':      'Leverkusen',
  'Leverkusen':            'Leverkusen',
  'RB Leipzig':            'RB Leipzig',
  'Leipzig':               'RB Leipzig',
  'Eintracht Frankfurt':   'Francfort',
  'Frankfurt':             'Francfort',
  'Freiburg':              'Fribourg',
  'SC Freiburg':           'Fribourg',
  'Wolfsburg':             'Wolfsburg',
  'VfL Wolfsburg':         'Wolfsburg',
  'Stuttgart':             'Stuttgart',
  'VfB Stuttgart':         'Stuttgart',
  'Hoffenheim':            'Hoffenheim',
  'Werder Bremen':         'Werder Brême',
  'Bremen':                'Werder Brême',
  'Augsburg':              'Augsbourg',
  'FC Augsburg':           'Augsbourg',
  'Union Berlin':          'Union Berlin',
  '1. FC Union Berlin':    'Union Berlin',
  'Heidenheim':            'Heidenheim',
  'Mainz':                 'Mayence',
  '1. FSV Mainz 05':       'Mayence',
  'Monchengladbach':       "M'gladbach",
  "Borussia M'gladbach":   "M'gladbach",
  'Cologne':               'Cologne',
  '1. FC Köln':            'Cologne',
  'Hamburg':               'Hambourg',
  'Hamburger SV':          'Hambourg',
  'St. Pauli':             'St. Pauli',
  'FC St. Pauli':          'St. Pauli',

  // ── Clubs — Serie A ────────────────────────────────────────────────────────
  'Napoli':                'Naples',
  'SSC Napoli':            'Naples',
  'Juventus':              'Juventus',
  'Inter Milan':           'Inter Milan',
  'Inter':                 'Inter Milan',
  'Internazionale':        'Inter Milan',
  'AC Milan':              'Milan AC',
  'Milan':                 'Milan AC',
  'AS Roma':               'Rome',
  'Roma':                  'Rome',
  'Lazio':                 'Lazio',
  'SS Lazio':              'Lazio',
  'Atalanta':              'Atalanta',
  'Fiorentina':            'Fiorentina',
  'ACF Fiorentina':        'Fiorentina',
  'Bologna':               'Bologne',
  'FC Bologna':            'Bologne',
  'Torino':                'Turin',
  'FC Torino':             'Turin',
  'Udinese':               'Udinese',
  'Cagliari':              'Cagliari',
  'Lecce':                 'Lecce',
  'Empoli':                'Empoli',
  'Verona':                'Vérone',
  'Hellas Verona':         'Vérone',
  'Genoa':                 'Gênes',
  'Monza':                 'Monza',
  'Frosinone':             'Frosinone',
  'Salernitana':           'Salernitana',
  'Como':                  'Côme',
  'Como 1907':             'Côme',
  'Parma':                 'Parme',
  'Venezia':               'Venise',
  'Pisa':                  'Pise',
  'AC Pisa':               'Pise',

  // ── Clubs — Coupes européennes ─────────────────────────────────────────────
  'PSV':                   'PSV Eindhoven',
  'PSV Eindhoven':         'PSV Eindhoven',
  'Ajax':                  'Ajax',
  'AFC Ajax':              'Ajax',
  'Feyenoord':             'Feyenoord',
  'Club Brugge':           'Bruges',
  'Anderlecht':            'Anderlecht',
  'Benfica':               'Benfica',
  'SL Benfica':            'Benfica',
  'Porto':                 'Porto',
  'FC Porto':              'Porto',
  'Sporting CP':           'Sporting CP',
  'Sporting Lisbon':       'Sporting CP',
  'Celtic':                'Celtic',
  'Rangers':               'Rangers',
  'Galatasaray':           'Galatasaray',
  'Fenerbahce':            'Fenerbahçe',
  'Besiktas':              'Beşiktaş',
  'Red Bull Salzburg':     'Salzbourg',
  'Salzburg':              'Salzbourg',
  'Shakhtar Donetsk':      'Chakhtior',
  'Olympiakos':            'Olympiakos',
  'Panathinaikos':         'Panathinaïkos',
  'Slavia Prague':         'Slavia Prague',
  'Slavia Praha':          'Slavia Prague',
  'Union Saint-Gilloise':  'Union Saint-Gilloise',
  'Union SG':              'Union Saint-Gilloise',
  'Bodø/Glimt':            'Bodø/Glimt',
  'Copenhagen':            'Copenhague',
  'FC Copenhagen':         'Copenhague',
  'København':             'Copenhague',
  'Qarabag':               'Qarabağ',
}

/**
 * Traduit un nom d'équipe ESPN en français.
 * Si aucune traduction trouvée, retourne le nom original.
 */
export function translateESPN(name) {
  if (!name) return name
  return ESPN_NAMES_FR[name] ?? name
}
